### ISSUE TITLE
Do you plan to convert this code into C++code? I think that's a good idea

### ISSUE THREAD

**Issue by GanWang** [Kazuhito00/XFeat-Image-Matching-ONNX-Sample#2]
Do you plan to convert this code into C++code? I think that's a good idea

**Comment by Kazuhito00** [comment]
There are no plans.

**Comment by bromotdi** [comment]
> Do you plan to convert this code into C++code? I think that's a good idea

Hi! Would you like to do this together? I have already done half the work..

**Comment by viborgen** [comment]
> > Do you plan to convert this code into C++code? I think that's a good idea
> 
> Hi! Would you like to do this together? I have already done half the work..

Did you end up finishing this?
